services:
  # Backend API service
  - type: web
    name: fantasy-agent-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd agent && python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  # Frontend web service
  - type: web
    name: fantasy-agent-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: REACT_APP_API_URL
        fromService:
          name: fantasy-agent-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL 