services:
  # Frontend web service
  - type: web
    name: fantasy-agent-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: REACT_APP_WEBSOCKET_URL
        value: wss://fantasy-agent.onrender.com/ws 